### ISSUE TITLE
[develop] automatically generated migrations require settings.FILER_IMAGE_MODEL

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-filer#1002]
With #1000 any 3rd party app creating a migration that uses ``FilerImageField`` will create an entry like this in the migrations:

```
migrations.AlterField(
    model_name='article',
    name='featured_image',
    field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.SET_NULL, verbose_name='featured image', blank=True, to=settings.FILER_IMAGE_MODEL, null=True),
),
```
And will fail to run because ``settings.FILER_IMAGE_MODEL`` is not set for most projects.
Is there a way to set a default for this value in settings?

**Comment by stefanfoulis** [comment]
@skirsdeda do you have advice on the issue?

**Comment by skirsdeda** [comment]
@stefanfoulis First it would make sense to have `get_image_model` function (something like https://github.com/django/django/blob/master/django/contrib/auth/__init__.py#L188). Then `FilerImageField` should have `deconstruct` method which would just skip `to` kwarg so that it doesn't appear in migrations while field's constructor could deal with calling `get_image_model` and then providing it to `to` kwarg.

**Comment by skirsdeda** [comment]
Thinking this over... Maybe it would be better if `deconstruct` had `to` with actual model name so that when `FILER_IMAGE_MODEL` setting changes, makemigrations would generate a new migration. After all, Django uses foreign key constraints at database level.
